# Generated by Django 4.1.7 on 2023-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patisserie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='cookies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='healthycookies',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
