# Generated by Django 4.1.7 on 2023-07-01 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patisserie', '0002_alter_cakes_image_alter_cookies_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patisserie.cakes')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patisserie.cart')),
                ('cookies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patisserie.cookies')),
                ('healthycookies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patisserie.healthycookies')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cakes',
            field=models.ManyToManyField(through='Patisserie.CartItem', to='Patisserie.cakes'),
        ),
        migrations.AddField(
            model_name='cart',
            name='cookies',
            field=models.ManyToManyField(through='Patisserie.CartItem', to='Patisserie.cookies'),
        ),
        migrations.AddField(
            model_name='cart',
            name='healthycookies',
            field=models.ManyToManyField(through='Patisserie.CartItem', to='Patisserie.healthycookies'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
